version: '3'
services:
  swagger-ui:
    build:
      context: swagger-ui
    environment:
      API_URL: http://localhost:8080/swagger.yaml
    ports:
      - "8080:8080"
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "8081:8080"
    depends_on:
      - swagger-ui
  web:
    build:
      context: ../.
      dockerfile: docker/node-api/Dockerfile
    ports:
      - "3000:3000"
